-- ============================================
-- ANALYTICS SYSTEM SETUP FOR SUPABASE
-- ============================================
-- Run this script in Supabase Dashboard > SQL Editor
-- This will create the analytics table and tracking function

-- 1. Create analytics table
CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE DEFAULT CURRENT_DATE NOT NULL,
  path TEXT NOT NULL,
  visits INT DEFAULT 1 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (date, path)
);

-- 2. Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_analytics_date ON analytics(date DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_path ON analytics(path);

-- 3. Create function to increment page views
CREATE OR REPLACE FUNCTION increment_page_view(page_path TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO analytics (date, path, visits, updated_at)
  VALUES (CURRENT_DATE, page_path, 1, NOW())
  ON CONFLICT (date, path)
  DO UPDATE SET 
    visits = analytics.visits + 1,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Create function to get analytics data (last 7 days)
CREATE OR REPLACE FUNCTION get_analytics_summary(days_back INT DEFAULT 7)
RETURNS TABLE (
  date DATE,
  total_visits BIGINT,
  unique_paths BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    a.date,
    SUM(a.visits)::BIGINT AS total_visits,
    COUNT(DISTINCT a.path)::BIGINT AS unique_paths
  FROM analytics a
  WHERE a.date >= CURRENT_DATE - days_back
  GROUP BY a.date
  ORDER BY a.date DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Enable Row Level Security (RLS)
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;

-- 6. Create policies for public access (read-only for anon, write for tracking)
-- Allow anyone to insert (for tracking)
CREATE POLICY "Allow public insert for tracking" 
  ON analytics FOR INSERT 
  WITH CHECK (true);

-- Allow authenticated users to read (for admin dashboard)
CREATE POLICY "Allow authenticated read" 
  ON analytics FOR SELECT 
  USING (auth.role() = 'authenticated');

-- Allow service role full access
CREATE POLICY "Allow service role all" 
  ON analytics FOR ALL 
  USING (auth.role() = 'service_role');

-- 7. Grant execute permissions on functions
GRANT EXECUTE ON FUNCTION increment_page_view(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION increment_page_view(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION increment_page_view(TEXT) TO service_role;

GRANT EXECUTE ON FUNCTION get_analytics_summary(INT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_analytics_summary(INT) TO service_role;

-- 8. Grant table permissions
GRANT INSERT ON analytics TO anon;
GRANT SELECT ON analytics TO authenticated;
GRANT ALL ON analytics TO service_role;

-- ============================================
-- VERIFICATION QUERIES (Optional - Run to test)
-- ============================================

-- Test the increment function
-- SELECT increment_page_view('/');
-- SELECT increment_page_view('/portfolio');

-- View current analytics
-- SELECT * FROM analytics ORDER BY date DESC, visits DESC;

-- Get summary
-- SELECT * FROM get_analytics_summary(7);

-- ============================================
-- SUCCESS! 
-- Your analytics system is now ready.
-- The website will automatically start tracking page views.
-- ============================================
