-- ============================================
-- ANALYTICS V2: ADVANCED VISITOR TRACKING
-- ============================================

-- 1. Create the visitor_logs table to store individual visits
CREATE TABLE IF NOT EXISTS visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ip_address TEXT,
    user_agent TEXT,
    device_type TEXT, -- 'Desktop', 'Mobile', 'Tablet', 'Unknown'
    country TEXT,
    city TEXT,
    path TEXT NOT NULL
);

-- 2. Create index for query performance
CREATE INDEX IF NOT EXISTS idx_visitor_logs_created_at ON visitor_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitor_logs_path ON visitor_logs(path);

-- 3. Enable RLS
ALTER TABLE visitor_logs ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Allow anyone (including anon API) to insert
CREATE POLICY "Allow public insert for logs" 
  ON visitor_logs FOR INSERT 
  WITH CHECK (true);

-- Allow admins (authenticated) to view logs
CREATE POLICY "Allow authenticated read logs" 
  ON visitor_logs FOR SELECT 
  USING (auth.role() = 'authenticated');

-- 5. Grant permissions
GRANT INSERT ON visitor_logs TO anon;
GRANT SELECT ON visitor_logs TO authenticated;
GRANT ALL ON visitor_logs TO service_role;

-- 6. Helper function to get recent visitors (Optional, can just query table directly)
CREATE OR REPLACE FUNCTION get_recent_visitors(limit_count INT DEFAULT 20)
RETURNS TABLE (
    id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    ip_address TEXT,
    device_type TEXT,
    country TEXT,
    city TEXT,
    path TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        v.id,
        v.created_at,
        v.ip_address,
        v.device_type,
        v.country,
        v.city,
        v.path
    FROM visitor_logs v
    ORDER BY v.created_at DESC
    LIMIT limit_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION get_recent_visitors(INT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_recent_visitors(INT) TO service_role;

-- ============================================
-- FINISHED
-- ============================================
